### ISSUE TITLE
please add a license 

### ISSUE THREAD

**Issue by DylanKojiCheslin** [kettanaito/naming-cheatsheet#1]

**Comment by kettanaito** [comment]
Hi, @DylanKojiCheslin. Thanks for reaching out!

What would be the reason for having a license for a cheatsheet?

**Comment by DylanKojiCheslin** [comment]
1. Reproduction: if people wanted to print a physical copy to keep by the computer, or even fork this repo it could be an legal issue. Sounds ridiculous but some companies are very specific about what open source code or data can be used.  

2. Derivative works: if someone were to make a IDE plugin that tested variable names based on the guidelines written here it could be a legal issue.  

3. Reuse: this cheat sheet would be awesome as a part of code review checklist but can't be a part of a defined process in a company without a license.

**Comment by kettanaito** [comment]
@DylanKojiCheslin, thanks for the examples.

I don't wish to restrict these guidelines. On the contrary, I would love to cooperate with people to put down a really valuable suggestions and practices to help others.

Please, if you have something to share, feel free to open an issue or a pull request! Closing this one.

**Comment by DylanKojiCheslin** [comment]
Thank you!
