### ISSUE TITLE
Use full variable names for `min`/`max` and `prev`/`next`

### ISSUE THREAD

**Issue by Richienb** [kettanaito/naming-cheatsheet#11]
Shouldn't these be `minimum`/`maximum` and `previous`/`next`?

**Comment by wflemingnz** [comment]
IMO the longer forms are unnecessarily verbose, while the meaning of the shorter forms is unambiguous.

**Comment by codingfriend1** [comment]
I think it might make more sense to do original/updated instead of previous/next. Previous/Next is more associated with links in pagination.

**Comment by kettanaito** [comment]
Hey, thanks for suggesting this, @Richienb!

I can't say I agree with the long forms of `min`/`max` and `prev`/`next`. There's certainly nothing wrong if you use their longer variations, but I find them taking more characters to write without much contribution to readability. 

> I think it might make more sense to do original/updated instead of prev/next. prev/next is more associated with links in pagination.

When referring to the state, the term "original" becomes ambiguous. The state is data over time, so "prev" and "next" makes sense as in "state of a data". I think "original" better suits "original"/"copy" pair than the state example.

**Comment by codingfriend1** [comment]
You make some good points! Original can be ambiguous and it does work well with copy. I might have to think on it some more
