### ISSUE TITLE
Include Note About Following Conventions of Specific Languages

### ISSUE THREAD

**Issue by ssimontis** [kettanaito/naming-cheatsheet#14]
First off, thank you for this great contribution! I think we all have wasted too much time trying to name things correctly and you did an excellent job summarizing how to name things well with minimal effort.

As I read through the first section, regarding casing, perhaps there should be a note to follow the conventions of your programming language? I know Python is very big on snake case, and it is often found in C, but would be completely out of place in a C# application. Some languages try very hard to establish conventions around PascalCasing or camelCasing variables.

If you agree that this is important, I would be happy to correct in a PR; I wanted to get your opinion on the matter first. Thank you again!

**Comment by ld-web** [comment]
I agree with this suggestion.

Another example is the PHP Standards Recommandations, and more specifically PSR-1 and the [Class Constants, Properties, and Methods](https://www.php-fig.org/psr/psr-1/#4-class-constants-properties-and-methods) section which focuses on how to name things. I guess it might vary from one language to another.

So, like you suggest @ssimontis, adding a note, or maybe create language-specific sections ?
I'm not sure about that though, might become a mess.

Also thanks for this repository, very helpful guidelines when trying to deal with the "naming things" issue 👍

**Comment by Aprillion** [comment]
I like that section how it is currently, aiming for consistency whatever option is chosen (if one or the other convention is chosen by the language's standard library, then it should be obvious which one to use in custom code,, and if someone doesn't want to follow conventions, then no amount of added text in that section may convince them otherwise).

**Comment by ld-web** [comment]
> I like that section how it is currently, aiming for consistency whatever option is chosen (if one or the other convention is chosen by the language's standard library, then it should be obvious which one to use in custom code,, and if someone doesn't want to follow conventions, then no amount of added text in that section may convince them otherwise).

I see, then I think #23 can be enough, just a general note !
