### ISSUE TITLE
handleLinkClick doesn't follow A/HC/LC Pattern

### ISSUE THREAD

**Issue by DavidArutiunian** [kettanaito/naming-cheatsheet#19]
```
prefix? + action (A) + high context (HC) + low context? (LC)
```

![image](https://user-images.githubusercontent.com/17799810/104850273-31c79400-58ff-11eb-92a0-19e53c89a685.png)
 
As per `A/HC/LC Pattern` it should be `handleClickLink`

**Comment by kettanaito** [comment]
Hey, @DavidArutiunian. 

Not necessarily. The pattern doesn't dictate which context should come first. Quite the opposite: it emphasizes that the order of contexts affects the meaning of a variable. This is mentioned here:

> Note: The order of context affects the meaning of a variable. For example,` shouldUpdateComponent` means you are about to update a component, while `shouldComponentUpdate` tells you that component will update on itself, and you are but controlling when it should be updated. In other words, high context emphasizes the meaning of a variable.

This applies to your suggestion as well. `handleClickLink` sounds unnatural and I think it hints that the last `link` is rather a "link that click possesses." 

High context is generally more descriptive (thus "high"), and in `handleLinkClick` it is more descriptive. `Link` may contain multiple events to handle, which makes it a more descriptive context than `Click`.
