### ISSUE TITLE
Use destroy instead of delete

### ISSUE THREAD

**Issue by lifeiscontent** [kettanaito/naming-cheatsheet#20]
delete is a reserved word in JavaScript and since this guide helps people decide in generic situations, I’m suggesting to use destroy instead of delete, because in cases where using the word delete are not possible we should be promoting a solution that works everywhere.

**Comment by kettanaito** [comment]
Hi, @lifeiscontent. Thanks for the suggestion.

While `delete` is a reserved keyword, these guidelines recommend using the phrase "delete" as an action prefix, meaning it always has another word(s) following it. There is no language violation that way. 

```js
deleteUser()
deletePost()
deleteItem()
```

> There is no connection with the `delete` keyword. 

The semantic meaning of "delete" is a great counterweight for "create", so I don't think we should stop recommending it.

**Comment by kettanaito** [comment]
"Destroy", on the other hand, is more the opposite to "construct" then "create" (my subjective opinion). "Destroy a post" doesn't read naturally, to be frank.

**Comment by lifeiscontent** [comment]
@kettanaito so I totally agree with you there. However it conflicts when being applied with "Avoid context duplication" as new developers are learning they might not know "delete" is a reserved word. And when you find something like this out, you're probably a bit far down the rabbit hole.

Anyway if you feel strongly about keeping it, that's fine I'd just urge you to at least put a warning so people are aware.

**Comment by kettanaito** [comment]
Hm. Perhaps I'm not seeing it from the same angle as you do. Could you elaborate more on why you think the reserved `delete` keyword is an issue?

I fail to see a problem here, as it's the same as `newUser` or `whileActive` where both `new` and `while` are reserved keywords. That doesn't make those variable names unsustainable or problematic.

**Comment by lifeiscontent** [comment]
it more or less has to do with working with objects.

for example, I couldn't define a function on a post called delete without it casuing issues.

```js
function Post() {};
Post.prototype.delete = function delete() {}; // Syntax error
```

**Comment by lifeiscontent** [comment]
ping @kettanaito

**Comment by silesky** [comment]
> it more or less has to do with working with objects.
> 
> 
> 
> for example, I couldn't define a function on a post called delete without it casuing issues.
> 
> 
> 
> ```js
> 
> function Post() {};
> 
> Post.prototype.delete = function delete() {}; // Syntax error
> 
> ```
> 
> 

LGTM 

Using a reserved  keyword in the global scope as a method on a class is not a code smell on any JS team I've ever worked with. If I see someone who defined a class method called "Address.with" "Address.for", I'm not going to flag it because it's a reserved word if used in the global scope.

**Comment by lifeiscontent** [comment]
@silesky I'm trying to be mindful of newer developers on a team, I'm not saying my suggestion is right, but more or less having a conversation about a topic that might have some tension around it. I understand how to solve this issue myself, but newer developers might run into it as something confusing.

I am curious what the maintainers of this project think about this kind of thing and what the recommendation would be for guiding new devs into a positive path, as unlike yourself, new devs don't have your knowledge of the language, and its important to be mindful of all developers alike that is how you build a solid community for everyone.

I plan on recommending this guide to my team and they all have various experiences with the language so I'd like it to be as welcoming as possible because I care about them and how they understand things vs the facts of how the language works.
