### ISSUE TITLE
Suggestion: Variable name for arrays

### ISSUE THREAD

**Issue by tomma5o** [kettanaito/naming-cheatsheet#24]
I don't remember in which style guide I've seen the following convention, but IMHO it makes sense.
Instead of using plurals, for naming variables that contains an array, just use "List"

For example:
#### Good
`var users = ['Gabri', 'Tom', 'Dave']`

#### Better
`var userList = ['Gabri', 'Tom', 'Dave']`

In large codebases is more readable **List** instead of **s**

So we can avoid:
`users.map(user => {})`
but use
`userList.map(user => {})`

**Comment by mantovanig** [comment]
It's a pretty strong rule, I agree about readability but it adds a lot of verbosity and repetition in variable names.  
Also this is a generic guideline and not just for JS, in other languages I think they use the word List to differentiate from Maps or other types. 

I think I prefer to enrich the name of the variable with what it contains:
`var userNames = ['Gabri', 'Tom', 'Dave']`

In this way we have more confidence about the type of value, names implies string.

**Comment by tomma5o** [comment]
Ok i don't know if there are some issue in some language but we find the same repetition in other cases for example in naming function like: **should**Update.

**users** or **userNames** doesn't fix the problem, i've used that just for example.

**Comment by mantovanig** [comment]
Yes probably it doesn't completely solve the problem you described and it doesn't fit with any situation but sometimes it can help.

Adding `List` or relative type (Array, Set, etc...) to all variable names is referred to as "Hungarian Notation", and is considered bad (and useless) practice especially if you are using a statically typed language. These are some useful references:
https://en.wikipedia.org/wiki/Hungarian_notation#Disadvantages

https://www.joelonsoftware.com/2005/05/11/making-wrong-code-look-wrong/

**Comment by fagnervalente** [comment]
Hi, I agree with in languages that there is a List type this have a different meaning, but in JS there are two more points to use.

- Some English words does not add 's' in the end in plural form and this contributes to typos for non-English speakers.
- Prefixes and suffixes do a better job of exposing the purpose of the variable

IMHO

**Comment by tomma5o** [comment]
I agree with @fagnervalente,
for example:
`policy → policies`

The Hungarian notation @mantovanig is an entire code style, here we are discussing just for arrays and just to understand the type at first glance like for boolean types (`isVisible`)

**Comment by mantovanig** [comment]
I don't think preventing typos for non-English speakers is the goal of these conventions, but maybe it can be for a specific team.

> The Hungarian notation @mantovanig is an entire code style, here we are discussing just for arrays and just to understand the type at first glance like for boolean types (isVisible)

It's a naming convention, and here we are discussing about naming conventions. The example about boolean types is a bit different, you are not repeating the type inside the name. IMHO

**Comment by tomma5o** [comment]
> It's a naming convention, and here we are discussing about naming conventions. The example about boolean types is a bit different, you are not repeating the type inside the name. IMHO

Yes is a naming convention but talk about all the types not only list and I agree with you naming things `fpBatteryPercentage` or `nSize` doesn't make any sense and personally I don't like it.

Btw Hungarian notation is a little bit different see example here:
https://en.wikipedia.org/wiki/Hungarian_notation#Examples

Hungarian `rgUser`
Proposal `userList`

**Comment by mantovanig** [comment]
I understand that your proposal is only for arrays but the concept is the same, except that in your proposal it is suffixed. 

> In Systems Hungarian notation, the prefix encodes the actual data type of the variable.

**Comment by tomma5o** [comment]
Btw List is only the way to define a plural not the type.

We have redundancy if we use for example `usersList`

**Comment by kettanaito** [comment]
Hey. Thanks for suggesting this. 

> Also this is a generic guideline and not just for JS, in other languages I think they use the word List to differentiate from Maps or other types.

This is an excellent point. "List" may indeed mean different things cross-languages and suggesting it in these guidelines may color them towards certain languages more than others. 

That being said (and I think I should mention this in the guidelines), none of the suggestions on this page are written in stone. It's possible to deviate from them and it's perfectly fine. One of such deviations may be the addition of the `List` suffix to a variable name that represents a list of values. There's nothing wrong with it. Just keep in mind that it's quite context-dependent and perhaps not generic enough to recommend.
