### ISSUE TITLE
[Translation] Add the chinese translation [zh-cn]

### ISSUE THREAD

**Issue by Turkyden** [kettanaito/naming-cheatsheet#32]
Add the chinese translation [zh-cn] , Thank you !

https://github.com/Turkyden/naming-cheatsheet

**Comment by kettanaito** [comment]
Hey, @Turkyden. Woah, thank you for the great job done on translating the document!

I think the original repo should remain written in English for maintenance reasons. I've had experience with multi-lingual projects and unless you have a language speaker in your team, translations can get out of date rather quickly. 

I do encourage you to keep your fork and periodically sync it with this repo!
