### ISSUE TITLE
Add scope and length rule

### ISSUE THREAD

**Issue by aes** [kettanaito/naming-cheatsheet#36]
There's a nice rule that suggests that the verbosity of names should be related to the size of the scope they're visible in.

E.g.
```
// good: the use and meaning of x is obvious
const example_doubled = example.map(x => x * 2);

// bad: sq and nn are unclear and the length of some_number obscures actual use
const sq = nn.map(some_number => some_number * some_number);
```

**Comment by kettanaito** [comment]
Hey, @aes. Thanks for the suggestions.

I can't say I share the love for `x`, `T`, and similar kinds of variables. While they can be interpreted from the context they are in, they still remain indiscernible in isolation. The more obvious the data behind a variable is based on its name, the better that variable is named. While the context may seem constant, it's not immune to changes in time. 

```js
// Here you can predict what `x` stands for from the context.
const example_doubled = example.map(x => x * 2)

// In time things change, people come and go,
// `examples` start coming from somewhere,
function a(examples) {
  // ... and the mapping logic grows and gets abstracted.
  examples.map(x => transformExample(x))
}
```

Suddenly the context has vanished and `x` doesn't stand for anything anymore. Consider if we named that argument descriptively from the start:

```js
// Now we can at least expect `number` to be some number.
examples.map(number => transformExample(number)

// We could have brought even more context to the agument name,
// making it more resilient to change:
examples.map(postsCount => transformExample(postsCount))
```

I would encourage meaningful variable naming regardless of the context:

```js
const numbers = [1, 2, 3].map(number => number * 2)
```

This plays nicely with both "avoid contractions", "don't duplicate context", and "S-I-D" patterns.

**Comment by aes** [comment]
For the record, I think it's not a great argument against, that people might not follow the rule in the future. As your example shows, it's really difficult to come up with a sensible name that adds anything. I believe that "number" is, at best, Hungarian notation, and as such can just as easily become untrue. But whatever, it's your rule set.

**Comment by kettanaito** [comment]
There is currently no discouragement against either `x` or `number`, which makes these guidelines neutral. This allows you to pick the right choice for you/your team and stick with it, applying the other encouraged principles like consistency and conciseness. 

I was against your suggestion not because it's bad in any way, but because discouraging something is a rather strong statement and yours doesn't qualify enough to be recommended in general.
