### ISSUE TITLE
Add recommendation on how to handle unsafe async / remote fetch functions

### ISSUE THREAD

**Issue by silesky** [kettanaito/naming-cheatsheet#39]
Currently the only fetch example is:
> function fetchPosts(postCount) {
>   return fetch('https://api.dev/posts', {...})
> }

“Fetch” is a synonym for get, and it — on its own —- implies a safe operation. How should we name unsafe operations that are also async, like update / delete etc?

to continue this pattern, we would expect:
- fetchPost
- fetchDeletePost 
- fetchCreatePost
... etc

Or, do we just forget the fetch altogether?

I’d like to propose just dropping the “fetchFoo” completely from the style guide, and not distinguish between fetching from a remote service or any other synchronous or asynchronous internal “getFoo” function. 

The semantics of “fetchFoo” only differ from “getFoo” in that they encode a data type in the name (a promise), which is a potential code smell. (see https://github.com/kettanaito/naming-cheatsheet/issues/37)

**Comment by kettanaito** [comment]
Hey, @silesky. Thanks for raising this.

I think the original suggestion of `fetchPosts` isn't the best one. I'd rather call it `getPosts` to highlight a data retrieval operation. In regards to other async actions, I'd name them after what they represent:

- `createPost`
- `updateUser`
- `deleteUser`

I see little value in a `fetch` prefix in these cases. 

What do you think about this?

**Comment by silesky** [comment]
> Hey, @silesky. Thanks for raising this.
> 
> 
> 
> I think the original suggestion of `fetchPosts` isn't the best one. I'd rather call it `getPosts` to highlight a data retrieval operation. In regards to other async actions, I'd name them after what they represent:
> 
> 
> 
> - `createPost`
> 
> - `updateUser`
> 
> - `deleteUser`
> 
> 
> 
> I see little value in a `fetch` prefix in these cases. 
> 
> 
> 
> What do you think about this? 

Completely agree!

**Comment by kettanaito** [comment]
Do you think we should remove the "fetch" action from the suggested ones?

**Comment by silesky** [comment]
> Do you think we should remove the "fetch" action from the suggested ones? 

Yes!
