### ISSUE TITLE
Suggested corrections in variable examples

### ISSUE THREAD

**Issue by ravihara** [kettanaito/naming-cheatsheet#4]
Hi, first of all, a very nice work on how to do better naming of Classes, Functions and Variables in programming! Thanks.

In the example, it looks better to show the distinction b/n a constant and a variable (Ex., talking the JS way)

```
const initialFruits  = 5;
let fruits = initialFruits;

function getFruits() {
return fruits;
}

function setFruits(newFruits) {
fruits = new Fruits;
}

function resetFruits() {
fruits = initialFruits;
}

```
Just my personal thoughts :-)

**Comment by kettanaito** [comment]
Thank you for the feedback, @ravihara. 

You're absolutely right, the current example contains a `const` re-assignment which is noop in ECMAScript. Would you be interested in shipping a pull request with your suggestions?

**Comment by ravihara** [comment]
> Thank you for the feedback, @ravihara.
> 
> You're absolutely right, the current example contains a `const` re-assignment which is noop in ECMAScript. Would you be interested in shipping a pull request with your suggestions?

Sure, will do.

**Comment by ravihara** [comment]
#5 Should be fixed in this pull request.

**Comment by georgettica** [comment]
If this was fixed in another PR, should this issue be closed as well?
