### ISSUE TITLE
isRoot or hasParent?

### ISSUE THREAD

**Issue by adam-devel** [kettanaito/naming-cheatsheet#41]
a node in a "parent pointing tree" which has no parent, is a root node.
should the method for checking that be `isRoot` or `hasParent` ?
also, should setting a node's parent have a method named `attach` or `setParent` ?

**Comment by adam-devel** [comment]
there doesn't seem to be any rule that govern this kind of situations

**Comment by kettanaito** [comment]
Hi, @adam-devel. 

Both `isRoot`/`isRootNode` and `hasParent` are valid names. I think your choice should be based on what characteristic of the node you are trying to capture. If you'd like to determine if a node is a root node, then use `isRoot`/`isRootNode`.
