### ISSUE TITLE
Incorrect order of arguments

### ISSUE THREAD

**Issue by Starojitski** [kettanaito/naming-cheatsheet#43]
The Context example has incorrect order of arguments, filter expects first predicate and then list. But it is called with posts list first and then predicate.

```
/* A pure function operating with primitives */
function filter(predicate, list) {
  return list.filter(predicate)
}

/* Function operating exactly on posts */
function getRecentPosts(posts) {
  return filter(posts, (post) => post.date === Date.now())
}
```

**Comment by kettanaito** [comment]
Hey, @Starojitski. This is a great find! You're right, the usage example is wrong. It should be:

```js
return filter((post) => post.date === Date.now(), posts)
```

Please, would you be interested in providing a pull request to fix this?
