### ISSUE TITLE
React prop: disabled Vs. isDisabled

### ISSUE THREAD

**Issue by gustavopch** [kettanaito/naming-cheatsheet#44]
In [Reflect the expected result](https://github.com/kettanaito/naming-cheatsheet/blob/9b1daf41af5d284fc4630035208f6ead9c9cdd2c/README.md#reflect-the-expected-result), is there a strong reason to name the prop `disabled` instead of `isDisabled`?
```js
const isDisabled = itemCount <= 3
return <Button disabled={isDisabled} />
```

**Comment by chiptus** [comment]
I think because a regular html button has the disabled prop.

**Comment by Turkyden** [comment]
React ? @gustavopch

**Comment by gustavopch** [comment]
@chiptus That's a good point. Now I'm wondering whether that pattern would also be recommended for regular function parameters:
```js
createButton({ disabled: isDisabled })
createButton({ isDisabled })
```
So here's another way to put it: where should booleans be prefixed with verbs and where not?
```js
// React components
const Button = ({ disabled }) => { ... }
const Button = ({ isDisabled }) => { ... }

// React components or maybe just regular functions
const renderButton = ({ disabled }) => { ... }
const renderButton = ({ isDisabled }) => { ... }

// Regular functions
const updateUser = ({ active }) => { ... }
const updateUser = ({ isActive }) => { ... }

// Objects
const user = { active: true }
const user = { isActive: true }
```
Can we have a simple and clear recommendation on that?

@Turkyden Sorry, I didn't get what you mean.

**Comment by kettanaito** [comment]
@chiptus has rightfully noticed that the prop name was preserved to be aligned with a similar attribute in HTML. When designing your own components/functions it's perfectly fine to use either `disabled` or `isDisabled`. I'd say the farther you are from an HTML context, the more `isDisabled` should favorable. 

I personally share the convention to prefix boolean variables with `is`/`has`/etc. as mentioned in these guidelines. It gives an instant reflection upon the variable's value upon reading.
