### ISSUE TITLE
Possible simplification of shouldDisplayPagination

### ISSUE THREAD

**Issue by wflemingnz** [kettanaito/naming-cheatsheet#6]
Great summary. 

One question/suggestion - wouldn’t:

`const shouldDisplayPagination = (postsCount > 10) // alternatively`

be better as:

`const shouldPaginate = (postsCount > 10) // alternatively `

The latter is more concise and I think expresses the  meaning better(though I could have the meaning wrong).

**Comment by kettanaito** [comment]
Hey, @wflemingnz. That's a great suggestion. Would you mind issuing a pull request that implements it?

**Comment by wflemingnz** [comment]
Yep, may be a week or so away though.
