### ISSUE TITLE
verb suggestions

### ISSUE THREAD

**Issue by sleak-lbl** [kettanaito/naming-cheatsheet#60]
This is a fantastic idea! I hope it becomes a common convention.

Related to #20, replacing `remove` with `drop` might help to avoid the remove/delete ambiguity.

I'm looking for what to call something that returns an iterator (in python), and think that `collect` is another good verb (`for i in foo.collectBars()`)

**Comment by kettanaito** [comment]
Thanks, @sleak-lbl!

> replacing remove with drop might help to avoid the remove/delete ambiguity.

It's a good suggestion, yet I'm not sure how agnostic "drop" is as a verb. It certainly comes to various languages adopting different vocabulary, but as a JavaScript engineer, I almost never see "drop" as an action in any API I use. Perhaps, dropping a database would be an exception.

**Comment by kettanaito** [comment]
I'm going to close this. I hope that the current state of the doc explains the difference between the ambiguous `remove`/`delete`. I once again remind everybody that these are just guidelines. **You can certainly deviate**. And what makes any guidelines good is finiteness.
