### ISSUE TITLE
Negative boolean variable names

### ISSUE THREAD

**Issue by jltwheeler** [kettanaito/naming-cheatsheet#63]
Suggestion to explain the best approach for naming negative booleans.

Example: if you create a variable for checking if an object is a dog , you could either do:

```js
const isDog = (dog) => dog.sound() === 'bark'

if (isDog(pet)) {
    // do something
}
```

or 

```js
const isNotDog = (dog) => dog.sound() !== 'bark'

if (isDog(pet)) {
    // do something
}
```

**Comment by kettanaito** [comment]
Thanks for the suggestion, @jltwheeler.

I'd suggest going with a positive `isDog` and negating it when necessary.

```js
const isDog = (dog) => dog.sound() === 'bark'

if (isDog(pet)) {
  // handle a situation when pet is a dog
}

if (!isDog(pet)) {
  // handle a situation when pet isn't a dog
}
```

I rarely encounter a need for negative boolean variables, so please feel free to reference any examples you see fit.
