### ISSUE TITLE
Counter-example to avoiding `a` as a variable name

### ISSUE THREAD

**Issue by demon** [kettanaito/naming-cheatsheet#65]
It's well accepted practice that this is an acceptable use of a single-letter variable:
```
for (x = 0; x < 10; x++) {
  // Do some stuff
} 
```
Worth noting, I think.

**Comment by kettanaito** [comment]
Hey, @demon. Thanks for mentioning this.

Excessively short names, such as `a` an `i`, fall under the [S-I-D paragraph](https://github.com/kettanaito/naming-cheatsheet#s-i-d) of the existing guidelines. While such variables are indeed short, they are not _descriptive_ neither _intuitive_. 

I'd generally recommend avoiding using one/two-letter abstract variable names "from the book". `i` can become a clear `index` and `a` may evolve into `currentUser`. There's 0 price to pay for descriptive names. There's a huge price to pay for unclear, deceptively short variables.
