### ISSUE TITLE
Questions about naming functions?

### ISSUE THREAD

**Issue by toFrankie** [kettanaito/naming-cheatsheet#79]
The article states that function names should follow the form: 

> `prefix? + Action (A) + High Context (HC) + Low Context? (LC)`

Next, the article explains the semantic difference between `shouldUpdateComponent()` and `shouldComponentUpdate()` in detail, and argues that the latter is more appropriate in React. I shouldn't have misunderstood it, please correct me if so, thanks!

However, `shouldComponentUpdate()` seems to be named differently than the `A/HC/LC` modes mentioned in the article.

* `shouldComponentUpdate` - prefix + HC + A
* `shouldUpdateComponent` - prefix + A + HC  😲

Based on the guidance in the article, it seems that `shouldUpdateComponent()` is more appropriate, right?

So, I'm a little confused 🤯, please clarify!

**Comment by kettanaito** [comment]
Hey, @toFrankie. A great question.

I explain this in the footnote (quote) of [A/HC/LC Pattern](https://github.com/kettanaito/naming-cheatsheet#ahclc-pattern):

> Note: The order of context affects the meaning of a variable. For example, shouldUpdateComponent means you are about to update a component, while shouldComponentUpdate tells you that component will update on itself, and you are but controlling when it should be updated. In other words, high context emphasizes the meaning of a variable.

I'm speaking about the order of the high context in this case:

```
A + HC // updateComponent
HC + A // componentUpdate
```

Please don't treat any of these recommendations as written in stone. Everything is flexible and depends on the use case. This document is a rather good starting point but you are most welcome to move things around, experiment, and break rules.
